### ISSUE TITLE
OpenCamera application on mac os x

### ISSUE THREAD

**Issue by manang** [barry-ran/learn-webrtc#1]
Hi,
I'm trying to use your application on mac os x, the problem is that on on_updateDeviceBtn_clicked

` std::unique_ptr<webrtc::VideoCaptureModule::DeviceInfo> info(
                webrtc::VideoCaptureFactory::CreateDeviceInfo());
    if (!info) {
        return;
    }`

info is always null.
how can I solve?
Thank you.
Angelo

**Comment by barry-ran** [comment]
You need to open camera permissions in permission management

**Comment by jankin-l** [comment]
@manang  @barry-ran it's not answer.
I had the same problem. Look at the source code 'modules/video_capture/video_capture_factory.cc' ,
WEBRTC_ANDROID and WEBRTC_MAC always return null
